[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"

[build.nixpacks]
providers = ["python", "node"]

[build.nixpacks.phases.setup]
cmds = [
    "cd frontend && npm install && npm run build"
]

[build.nixpacks.phases.install]
cmds = [
    "pip install -r requirements.txt"
]