[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port $PORT"

[build.nixpacks]
providers = ["python", "node"]

[build.nixpacks.phases.setup]
cmds = [
    "cd frontend && npm install && npm run build",
    "cd backend && pip install -r requirements.txt"
]
